-- ================================================================
-- SmartStat AI — Edge provenance + extra audit RPC
-- ================================================================
-- Adds nav_edges.source so the UI can render manual edges differently
-- from edges generated by the auto-connect routine. Existing edges are
-- marked 'auto' (they were created by the seed or by connect_node_to_nearest).
-- ================================================================

do $$
begin
  if not exists (select 1 from pg_type where typname = 'nav_edge_source') then
    create type nav_edge_source as enum ('auto', 'manual', 'seed');
  end if;
end$$;

alter table public.nav_edges
  add column if not exists source nav_edge_source not null default 'auto';

-- Backfill: anything created by the seed migration (003) we leave as 'auto'
-- since visually it's auto-generated for the demo. Future inserts from the
-- UI will set source = 'manual' explicitly.

-- Auto-connect function should mark its edges as 'auto'
create or replace function public.connect_node_to_nearest(
  p_node_id uuid,
  k int default 3,
  max_distance_m double precision default 15.0
)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_floor_id uuid;
  v_tenant_id uuid;
  v_x double precision;
  v_y double precision;
  v_inserted int := 0;
begin
  select floor_id, tenant_id, position_x, position_y
    into v_floor_id, v_tenant_id, v_x, v_y
  from public.nav_nodes where id = p_node_id;

  if v_floor_id is null then return 0; end if;

  with candidates as (
    select n.id,
           sqrt(power(n.position_x - v_x, 2) + power(n.position_y - v_y, 2)) as d
    from public.nav_nodes n
    where n.floor_id = v_floor_id
      and n.id <> p_node_id
      and sqrt(power(n.position_x - v_x, 2) + power(n.position_y - v_y, 2)) <= max_distance_m
    order by d asc
    limit k
  ),
  inserts as (
    insert into public.nav_edges (
      tenant_id, from_node_id, to_node_id, distance_meters,
      wheelchair_accessible, one_way, source
    )
    select v_tenant_id, p_node_id, c.id, c.d, true, false, 'auto'
    from candidates c
    on conflict (from_node_id, to_node_id) do nothing
    returning 1
  ),
  inserts_back as (
    insert into public.nav_edges (
      tenant_id, from_node_id, to_node_id, distance_meters,
      wheelchair_accessible, one_way, source
    )
    select v_tenant_id, c.id, p_node_id, c.d, true, false, 'auto'
    from candidates c
    on conflict (from_node_id, to_node_id) do nothing
    returning 1
  )
  select count(*) into v_inserted from (
    select * from inserts union all select * from inserts_back
  ) all_inserts;

  return v_inserted;
end;
$$;

-- regenerate_floor_graph should clear ONLY auto edges, preserving manual ones
create or replace function public.regenerate_floor_graph(
  p_floor_id uuid,
  k int default 3,
  max_distance_m double precision default 15.0
)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total int := 0;
  v_node record;
begin
  -- Wipe only auto-generated edges; manual edges drawn by admins survive
  delete from public.nav_edges e
  using public.nav_nodes n
  where (e.from_node_id = n.id or e.to_node_id = n.id)
    and n.floor_id = p_floor_id
    and e.source = 'auto';

  for v_node in
    select id from public.nav_nodes where floor_id = p_floor_id
  loop
    v_total := v_total + public.connect_node_to_nearest(v_node.id, k, max_distance_m);
  end loop;

  return v_total;
end;
$$;
